# Logging settings.
logging:
  level: INFO
  loggers:
    com.filipesilvestre: DEBUG

# Server settings.
server:
  applicationContextPath: /
  type: simple
  connector:
    type: http
    port: 9000

database:
  driverClass: org.h2.Driver
  user: sa
#  password:
  url: jdbc:h2:./target/beerme
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: validate # validates schema when service is started